#Dockerfile
#Mysql
#Red
#Volume
#Env

services:

    api:
        build: .
        container_name: api_usuarios
        ports:
            - "3002:3000"
        depends_on:
            - db
        environment:
            - PORT: 3306
            - DB_HOST: db
            - DB_USER: root
            - DB_PASSWORD: rootpassword
            - DB_NAME: db_usuarios
        networks:
            - app-network

    db:
        image: mysql:8
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: db_usuarios
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3310:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network
volumes:
    mysql_data:

networks:
    app-network:
